# Generated by Django 4.2.7 on 2026-04-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_add_paper_upload_and_exam_setter'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
