# Generated by Django 4.2.7 on 2026-05-01 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0003_emailrecipient_provider_id_pushnotificationlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationDispatchTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("WHATSAPP", "WhatsApp"), ("PUSH", "Push")], max_length=20)),
                ("status", models.CharField(choices=[("Queued", "Queued"), ("Processing", "Processing"), ("Sent", "Sent"), ("Failed", "Failed")], db_index=True, default="Queued", max_length=20)),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("recipient", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("dedupe_key", models.CharField(max_length=160, unique=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("available_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("provider_id", models.CharField(blank=True, max_length=120)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["available_at", "id"],
            },
        ),
    ]
