# Generated by Codex on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_department_school_bridge_and_employee_field_relaxation"),
        ("staff_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="hr_employee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_mgmt_profile",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="staffdepartment",
            name="hr_department",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_mgmt_profile",
                to="hr.department",
            ),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="hr_attendance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_mgmt_profile",
                to="hr.attendancerecord",
            ),
        ),
    ]
