# Generated by Codex on 2026-03-30

from datetime import date, datetime
from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations


STAFF_TO_HR_EMPLOYMENT_TYPE = {
    "Full-time": "Full-time",
    "Part-time": "Part-time",
    "Contract": "Contract",
    "Visiting": "Temporary",
}

STAFF_TO_HR_STATUS = {
    "Active": "Active",
    "On Leave": "On Leave",
    "Suspended": "Suspended",
    "Resigned": "Terminated",
    "Retired": "Retired",
}


def _normalize_name(value):
    return "".join(char for char in (value or "").lower() if char.isalnum())


def _generate_employee_id(Employee):
    year = date.today().year
    prefix = f"EMP-{year}-"
    last = (
        Employee.objects.filter(employee_id__startswith=prefix)
        .order_by("-employee_id")
        .values_list("employee_id", flat=True)
        .first()
    )
    if not last:
        sequence = 1
    else:
        try:
            sequence = int(last.split("-")[-1]) + 1
        except (TypeError, ValueError, IndexError):
            sequence = Employee.objects.count() + 1
    return f"{prefix}{sequence:03d}"


def _calculate_hours_worked(clock_in, clock_out):
    if not clock_in or not clock_out:
        return Decimal("0.00")
    start = datetime.combine(date.today(), clock_in)
    end = datetime.combine(date.today(), clock_out)
    seconds = max(0, int((end - start).total_seconds()))
    return (Decimal(seconds) / Decimal("3600")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def _find_matching_employee(Employee, StaffMember, staff_member):
    if staff_member.user_id:
        user_matches = Employee.objects.filter(user_id=staff_member.user_id)
        if user_matches.count() == 1:
            candidate = user_matches.first()
            if not StaffMember.objects.filter(hr_employee_id=candidate.id).exclude(pk=staff_member.pk).exists():
                return candidate
    if staff_member.staff_id:
        id_matches = Employee.objects.filter(employee_id=staff_member.staff_id)
        if id_matches.count() == 1:
            candidate = id_matches.first()
            if not StaffMember.objects.filter(hr_employee_id=candidate.id).exclude(pk=staff_member.pk).exists():
                return candidate
    name_matches = Employee.objects.filter(
        first_name__iexact=staff_member.first_name,
        last_name__iexact=staff_member.last_name,
    )
    if staff_member.middle_name:
        name_matches = name_matches.filter(middle_name__iexact=staff_member.middle_name)
    if staff_member.join_date:
        name_matches = name_matches.filter(join_date=staff_member.join_date)
    if staff_member.date_of_birth:
        name_matches = name_matches.filter(date_of_birth=staff_member.date_of_birth)
    if name_matches.count() == 1:
        candidate = name_matches.first()
        if not StaffMember.objects.filter(hr_employee_id=candidate.id).exclude(pk=staff_member.pk).exists():
            return candidate
    return None


def _find_matching_department(HrDepartment, StaffDepartment, staff_department):
    if staff_department.code:
        code_matches = HrDepartment.objects.filter(code=staff_department.code)
        if code_matches.count() == 1:
            candidate = code_matches.first()
            if not StaffDepartment.objects.filter(hr_department_id=candidate.id).exclude(pk=staff_department.pk).exists():
                return candidate
    normalized_name = _normalize_name(staff_department.name)
    if not normalized_name:
        return None
    candidates = []
    for department in HrDepartment.objects.all():
        if _normalize_name(department.name) == normalized_name:
            candidates.append(department)
        if len(candidates) > 1:
            break
    if len(candidates) == 1:
        candidate = candidates[0]
        if not StaffDepartment.objects.filter(hr_department_id=candidate.id).exclude(pk=staff_department.pk).exists():
            return candidate
    return None


def _ensure_school_department_shadow(SchoolDepartment, HrDepartment, hr_department):
    school_department = None
    if hr_department.school_department_id:
        school_department = SchoolDepartment.objects.filter(pk=hr_department.school_department_id).first()
    target_name = (hr_department.name or "").strip() or hr_department.code
    head_user_id = None
    if hr_department.head_id:
        head_user_id = hr_department.head.user_id

    if school_department is None:
        school_department = SchoolDepartment.objects.filter(name__iexact=target_name).first()
        if school_department and HrDepartment.objects.filter(school_department_id=school_department.id).exclude(pk=hr_department.pk).exists():
            school_department = None
        if school_department is None:
            school_department = SchoolDepartment.objects.create(
                name=target_name,
                description=hr_department.description or "",
                head_id=head_user_id,
                is_active=hr_department.is_active,
            )

    update_fields = []
    if school_department.name != target_name and not SchoolDepartment.objects.filter(name__iexact=target_name).exclude(pk=school_department.pk).exists():
        school_department.name = target_name
        update_fields.append("name")
    if school_department.description != (hr_department.description or ""):
        school_department.description = hr_department.description or ""
        update_fields.append("description")
    if school_department.head_id != head_user_id:
        school_department.head_id = head_user_id
        update_fields.append("head")
    if school_department.is_active != hr_department.is_active:
        school_department.is_active = hr_department.is_active
        update_fields.append("is_active")
    if update_fields:
        school_department.save(update_fields=update_fields)

    if hr_department.school_department_id != school_department.id:
        hr_department.school_department_id = school_department.id
        hr_department.save(update_fields=["school_department"])

    return school_department


def backfill_staff_bridges(apps, schema_editor):
    StaffMember = apps.get_model("staff_mgmt", "StaffMember")
    StaffDepartment = apps.get_model("staff_mgmt", "StaffDepartment")
    StaffAssignment = apps.get_model("staff_mgmt", "StaffAssignment")
    StaffAttendance = apps.get_model("staff_mgmt", "StaffAttendance")
    Employee = apps.get_model("hr", "Employee")
    HrDepartment = apps.get_model("hr", "Department")
    HrAttendanceRecord = apps.get_model("hr", "AttendanceRecord")
    SchoolDepartment = apps.get_model("school", "Department")

    processed_departments = set()

    def sync_department(staff_department):
        if not staff_department or staff_department.pk in processed_departments:
            return HrDepartment.objects.filter(pk=staff_department.hr_department_id).first() if staff_department else None
        if staff_department.parent_id and not staff_department.parent.hr_department_id:
            sync_department(staff_department.parent)

        hr_department = _find_matching_department(HrDepartment, StaffDepartment, staff_department)
        if hr_department is None:
            hr_department = HrDepartment(code=staff_department.code)
        hr_department.name = staff_department.name
        hr_department.code = staff_department.code
        hr_department.description = staff_department.description or ""
        hr_department.is_active = staff_department.is_active
        hr_department.parent_id = staff_department.parent.hr_department_id if staff_department.parent_id and staff_department.parent.hr_department_id else None
        hr_department.save()
        _ensure_school_department_shadow(SchoolDepartment, HrDepartment, hr_department)
        if staff_department.hr_department_id != hr_department.id:
            staff_department.hr_department_id = hr_department.id
            staff_department.save(update_fields=["hr_department"])
        processed_departments.add(staff_department.pk)
        return hr_department

    for staff_department in StaffDepartment.objects.all().select_related("parent").order_by("id"):
        sync_department(staff_department)

    for staff_member in StaffMember.objects.all().order_by("id"):
        employee = _find_matching_employee(Employee, StaffMember, staff_member)
        if employee is None:
            employee = Employee(employee_id=_generate_employee_id(Employee))
        employee.user_id = staff_member.user_id
        employee.first_name = staff_member.first_name
        employee.middle_name = staff_member.middle_name
        employee.last_name = staff_member.last_name
        employee.date_of_birth = staff_member.date_of_birth
        employee.gender = staff_member.gender or "Other"
        employee.nationality = staff_member.nationality or ""
        employee.employment_type = STAFF_TO_HR_EMPLOYMENT_TYPE.get(staff_member.employment_type, "Full-time")
        employee.status = STAFF_TO_HR_STATUS.get(staff_member.status, "Active")
        employee.join_date = staff_member.join_date
        employee.exit_date = staff_member.exit_date
        employee.is_active = staff_member.is_active
        employee.save()
        if staff_member.hr_employee_id != employee.id:
            staff_member.hr_employee_id = employee.id
            staff_member.save(update_fields=["hr_employee"])

    for staff_department in StaffDepartment.objects.filter(hr_department__isnull=False).select_related("head", "hr_department").order_by("id"):
        hr_department = staff_department.hr_department
        if staff_department.head_id and staff_department.head.hr_employee_id:
            hr_department.head_id = staff_department.head.hr_employee_id
        else:
            hr_department.head_id = None
        hr_department.save(update_fields=["head"])
        _ensure_school_department_shadow(SchoolDepartment, HrDepartment, hr_department)

    staff_ids = StaffAssignment.objects.filter(is_active=True).values_list("staff_id", flat=True).distinct()
    for staff_id in staff_ids:
        assignment = (
            StaffAssignment.objects.filter(staff_id=staff_id, is_active=True)
            .select_related("department")
            .order_by("-is_primary", "-effective_from", "-id")
            .first()
        )
        if not assignment:
            continue
        staff_member = StaffMember.objects.filter(pk=staff_id).first()
        if not staff_member or not staff_member.hr_employee_id:
            continue
        department = assignment.department
        if not department or not department.hr_department_id:
            continue
        hr_department = HrDepartment.objects.filter(pk=department.hr_department_id).first()
        if not hr_department:
            continue
        school_department = _ensure_school_department_shadow(SchoolDepartment, HrDepartment, hr_department)
        Employee.objects.filter(pk=staff_member.hr_employee_id).update(department_id=school_department.id)

    for attendance in StaffAttendance.objects.filter(is_active=True).select_related("staff").order_by("id"):
        if not attendance.staff_id or not attendance.staff.hr_employee_id:
            continue
        defaults = {
            "clock_in": attendance.clock_in,
            "clock_out": attendance.clock_out,
            "status": attendance.status,
            "hours_worked": _calculate_hours_worked(attendance.clock_in, attendance.clock_out),
            "overtime_hours": Decimal("0.00"),
            "notes": attendance.notes or "",
            "recorded_by_id": attendance.marked_by_id,
            "is_active": attendance.is_active,
        }
        hr_attendance, _ = HrAttendanceRecord.objects.update_or_create(
            employee_id=attendance.staff.hr_employee_id,
            date=attendance.date,
            defaults=defaults,
        )
        if attendance.hr_attendance_id != hr_attendance.id:
            attendance.hr_attendance_id = hr_attendance.id
            attendance.save(update_fields=["hr_attendance"])


class Migration(migrations.Migration):

    dependencies = [
        ("staff_mgmt", "0002_staff_bridge_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_staff_bridges, migrations.RunPython.noop),
    ]
