# Generated by Django 4.2.7 on 2026-04-05 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0014_custom_domain_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=120)),
                ("key_prefix", models.CharField(max_length=40)),
                ("key_last_four", models.CharField(max_length=8)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_api_keys_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_api_keys",
                        to="clients.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="platformapikey",
            index=models.Index(fields=["tenant", "is_active"], name="clients_pla_tenant__a0c666_idx"),
        ),
        migrations.AddIndex(
            model_name="platformapikey",
            index=models.Index(fields=["created_at"], name="clients_pla_created_633e84_idx"),
        ),
    ]
