# Generated by Django 4.2.7 on 2026-04-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_platformapikey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformapikey',
            new_name='clients_pla_tenant__e9175d_idx',
            old_name='clients_pla_tenant__a0c666_idx',
        ),
        migrations.RenameIndex(
            model_name='platformapikey',
            new_name='clients_pla_created_02e2ad_idx',
            old_name='clients_pla_created_633e84_idx',
        ),
    ]
