# Generated by Django 4.2.7 on 2026-04-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_rename_clients_pla_tenant__a0c666_idx_clients_pla_tenant__e9175d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, help_text='Tenant schema this revenue came from', max_length=63)),
                ('school_name', models.CharField(blank=True, help_text='School name for display', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('TRANSACTION_FEE', 'Transaction Fee'), ('SUBSCRIPTION', 'Subscription'), ('SETUP_FEE', 'Setup Fee'), ('CUSTOM', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('mpesa_receipt', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_logs', to='clients.tenantsubscription')),
            ],
            options={
                'verbose_name': 'Revenue Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['schema_name', 'source', 'created_at'], name='clients_rev_schema__39801d_idx'), models.Index(fields=['created_at'], name='clients_rev_created_d26cf6_idx')],
            },
        ),
    ]
