# Generated by Django 4.2.7 on 2026-04-27 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import clients.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0017_revenue_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDataImportRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "import_profile",
                    models.CharField(
                        choices=[
                            ("LEGACY_WORKBOOK_BUNDLE", "Legacy workbook bundle"),
                            ("MANUAL_ARCHIVE", "Manual archive"),
                        ],
                        default="LEGACY_WORKBOOK_BUNDLE",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("source_system", models.CharField(blank=True, max_length=120)),
                ("source_reference", models.CharField(blank=True, max_length=120)),
                ("school_name_override", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("archive_raw_to_media", models.BooleanField(default=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_data_import_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_import_requests",
                        to="clients.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status"], name="clients_ten_status_38ac6e_idx"),
                    models.Index(fields=["import_profile"], name="clients_ten_import__2422df_idx"),
                    models.Index(fields=["created_at"], name="clients_ten_created_217ff6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantDataImportFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=clients.models._platform_import_attachment_path)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="clients.tenantdataimportrequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_data_import_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="tenantdataimportfile",
            constraint=models.UniqueConstraint(
                fields=("import_request", "original_name"),
                name="clients_data_import_file_unique_name_per_request",
            ),
        ),
    ]
