# Generated by Django 4.2.7 on 2026-03-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0048_tenant_settings_locale_finance"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="ulid",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=26, null=True),
        ),
    ]
