# Generated by Django 4.2.7 on 2026-03-30 06:05

import secrets
import time

from django.db import migrations


_CROCKFORD_BASE32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def _generate_ulid():
    timestamp_ms = int(time.time() * 1000)
    randomness = int.from_bytes(secrets.token_bytes(10), "big")
    value = (timestamp_ms << 80) | randomness

    chars = []
    for _ in range(26):
        chars.append(_CROCKFORD_BASE32[value & 0x1F])
        value >>= 5
    return "".join(reversed(chars))


def backfill_student_ulids(apps, schema_editor):
    Student = apps.get_model("school", "Student")
    queryset = Student.objects.filter(ulid__isnull=True).order_by("pk")

    for student in queryset.iterator(chunk_size=500):
        ulid = _generate_ulid()
        while Student.objects.filter(ulid=ulid).exists():
            ulid = _generate_ulid()
        student.ulid = ulid
        student.save(update_fields=["ulid"])


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0049_student_add_ulid"),
    ]

    operations = [
        migrations.RunPython(backfill_student_ulids, migrations.RunPython.noop),
    ]
