# Generated by Django 4.2.7 on 2026-03-30 06:05

from django.db import migrations, models

import school.identity


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0050_backfill_student_ulid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="ulid",
            field=models.CharField(
                db_index=True,
                default=school.identity.generate_ulid,
                editable=False,
                max_length=26,
                unique=True,
            ),
        ),
    ]
