# Generated by Django 4.2.7 on 2026-04-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_session5_role_scope_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='vote_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='school.votehead'),
        ),
    ]
