# Generated by Django 4.2.7 on 2026-04-03 08:30

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0055_journalline_vote_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionSecurityPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "session_timeout_minutes",
                    models.PositiveIntegerField(default=60, validators=[MinValueValidator(5)]),
                ),
                (
                    "max_login_attempts",
                    models.PositiveIntegerField(default=5, validators=[MinValueValidator(1)]),
                ),
                (
                    "lockout_duration_minutes",
                    models.PositiveIntegerField(default=15, validators=[MinValueValidator(1)]),
                ),
                (
                    "min_password_length",
                    models.PositiveIntegerField(default=8, validators=[MinValueValidator(6)]),
                ),
                ("require_uppercase", models.BooleanField(default=True)),
                ("require_numbers", models.BooleanField(default=True)),
                ("require_special_characters", models.BooleanField(default=False)),
                ("password_expiry_days", models.PositiveIntegerField(default=90)),
                (
                    "mfa_mode",
                    models.CharField(
                        choices=[
                            ("DISABLED", "Disabled"),
                            ("ADMIN_ONLY", "Admin only"),
                            ("ALL_STAFF", "All staff"),
                        ],
                        default="DISABLED",
                        max_length=20,
                    ),
                ),
                (
                    "mfa_method",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("TOTP", "Authenticator app"),
                        ],
                        default="SMS",
                        max_length=10,
                    ),
                ),
                ("ip_whitelist_enabled", models.BooleanField(default=False)),
                ("allowed_ip_ranges", models.JSONField(blank=True, default=list)),
                (
                    "audit_log_retention_days",
                    models.PositiveIntegerField(default=365, validators=[MinValueValidator(30)]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_institution_security_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Security Policy",
                "verbose_name_plural": "Institution Security Policies",
            },
        ),
    ]
