# Generated by Django 4.2.7 on 2026-04-03 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0056_institutionsecuritypolicy_control_plane"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionLifecycleTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("TENANT_ONBOARDING", "Tenant onboarding"),
                            ("TERM_START", "Term start"),
                            ("YEAR_CLOSE", "Year close"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Institution Lifecycle Template",
                "verbose_name_plural": "Institution Lifecycle Templates",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionLifecycleRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In progress"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_institution_lifecycle_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_institution_lifecycle_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institution_lifecycle_runs",
                        to="school.academicyear",
                    ),
                ),
                (
                    "target_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institution_lifecycle_runs",
                        to="school.term",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="school.institutionlifecycletemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Lifecycle Run",
                "verbose_name_plural": "Institution Lifecycle Runs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionLifecycleTaskTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("task_group", models.CharField(blank=True, max_length=80)),
                ("required", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("waivable", models.BooleanField(default=False)),
                ("validation_key", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_templates",
                        to="school.institutionlifecycletemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Lifecycle Task Template",
                "verbose_name_plural": "Institution Lifecycle Task Templates",
                "ordering": ["template_id", "display_order", "id"],
                "unique_together": {("template", "task_code")},
            },
        ),
        migrations.CreateModel(
            name="InstitutionLifecycleTaskRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("WAIVED", "Waived"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("waived_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("blocker_message", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_institution_lifecycle_task_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_runs",
                        to="school.institutionlifecyclerun",
                    ),
                ),
                (
                    "template_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_runs",
                        to="school.institutionlifecycletasktemplate",
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waived_institution_lifecycle_task_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Lifecycle Task Run",
                "verbose_name_plural": "Institution Lifecycle Task Runs",
                "ordering": ["display_order", "id"],
                "unique_together": {("run", "template_task")},
            },
        ),
    ]
