# Generated by Django 4.2.7 on 2026-04-16 11:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0058_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('alert_type', models.CharField(choices=[('HIGH_RISK_TRANSACTION_BLOCKED', 'High Risk Transaction Blocked'), ('ELEVATED_RISK_TRANSACTION', 'Elevated Risk Transaction'), ('DUPLICATE_RECEIPT', 'Duplicate Receipt Detected'), ('RECONCILIATION_MISMATCH', 'Reconciliation Mismatch'), ('OVERDRAFT_ATTEMPT', 'Overdraft Attempt'), ('SUSPICIOUS_PATTERN', 'Suspicious Pattern Detected'), ('VOLUME_SPIKE', 'Unusual Volume Spike'), ('MANY_FAILURES', 'Many Failed Transactions'), ('ACTIVITY_SPIKE', 'Activity Spike'), ('ROUND_AMOUNT_PATTERN', 'Round Amount Pattern'), ('PHONE_MISMATCH', 'Phone Number Mismatch'), ('DAILY_VOLUME_LIMIT', 'Daily Volume Limit Exceeded'), ('NEW_USER_LARGE_TX', 'New User Large Transaction'), ('MISSING_RECEIPT', 'Missing M-Pesa Receipt')], max_length=50)),
                ('message', models.TextField()),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('BALANCED', 'Balanced'), ('MISMATCH', 'Mismatch Found'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_entries', models.IntegerField(default=0)),
                ('total_credits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_debits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('discrepancies', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Reconciliation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('BALANCE_UPDATED', 'Balance Updated'), ('BALANCE_ADJUSTED', 'Balance Adjusted by Admin'), ('STK_PUSH_INITIATED', 'STK Push Initiated'), ('STK_PUSH_CALLBACK', 'STK Push Callback Received'), ('WALLET_CREDITED', 'Wallet Credited'), ('WALLET_DEBITED', 'Wallet Debited'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('INVOICE_CREATED', 'Invoice Created'), ('INVOICE_PAID', 'Invoice Paid'), ('INVOICE_CANCELLED', 'Invoice Cancelled'), ('FRAUD_ALERT_RAISED', 'Fraud Alert Raised'), ('FRAUD_ALERT_RESOLVED', 'Fraud Alert Resolved'), ('ADMIN_ACTION', 'Admin Action'), ('EXPORT_GENERATED', 'Export Generated')], db_index=True, max_length=50)),
                ('entity', models.CharField(help_text='TRANSACTION, WALLET, INVOICE, etc', max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('entry_hash', models.CharField(db_index=True, max_length=64)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'indexes': [models.Index(fields=['user'], name='school_wall_user_id_29e173_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_score', models.IntegerField(help_text='0-100')),
                ('factors', models.JSONField(default=list)),
                ('action_taken', models.CharField(choices=[('ALLOW', 'Allowed'), ('FLAG', 'Flagged'), ('BLOCK', 'Blocked')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.fraudalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Score Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='school_risk_user_id_f7007c_idx'), models.Index(fields=['risk_score'], name='school_risk_risk_sc_755256_idx'), models.Index(fields=['action_taken'], name='school_risk_action__82ae1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit, negative = debit', max_digits=12)),
                ('entry_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('FEE_PAYMENT', 'Fee Payment'), ('REFUND', 'Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('TRANSACTION_FEE', 'Transaction Fee'), ('SCHOOL_CREDIT', 'School Credit'), ('SCHOOL_FEE', 'School Fee'), ('PENALTY', 'Penalty'), ('DISCOUNT', 'Discount')], max_length=20)),
                ('reference', models.CharField(db_index=True, help_text='M-Pesa receipt, invoice number, etc', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='school_ledg_user_id_e4308a_idx'), models.Index(fields=['reference'], name='school_ledg_referen_810122_idx'), models.Index(fields=['entry_type', 'created_at'], name='school_ledg_entry_t_5e3e87_idx')],
            },
        ),
        migrations.CreateModel(
            name='FraudWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_type', models.CharField(choices=[('PHONE', 'Phone Number'), ('USER', 'User'), ('IP', 'IP Address')], max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whitelisted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Whitelist Entry',
                'unique_together': {('whitelist_type', 'value')},
            },
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['level', 'resolved'], name='school_frau_level_38fefc_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['alert_type'], name='school_frau_alert_t_a124e9_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['created_at'], name='school_frau_created_82378e_idx'),
        ),
        migrations.AddIndex(
            model_name='financeauditlog',
            index=models.Index(fields=['action', 'created_at'], name='school_fina_action_2b0ace_idx'),
        ),
        migrations.AddIndex(
            model_name='financeauditlog',
            index=models.Index(fields=['entity', 'entity_id'], name='school_fina_entity_ccbbe0_idx'),
        ),
        migrations.AddIndex(
            model_name='financeauditlog',
            index=models.Index(fields=['user', 'created_at'], name='school_fina_user_id_839d73_idx'),
        ),
        migrations.AddIndex(
            model_name='financeauditlog',
            index=models.Index(fields=['created_at'], name='school_fina_created_c2ea9c_idx'),
        ),
    ]
