# Generated by Django 4.2.7 on 2026-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_wallet_ledger_fraud_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeauditlog',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Explicitly set before save to ensure hash stability', null=True),
        ),
    ]
