# Generated by Django 4.2.7 on 2026-04-21 10:00

from django.db import migrations, models


ROLE_NAME_CHOICES = [
    ('TENANT_SUPER_ADMIN', 'Tenant Super Admin'),
    ('ADMIN', 'School Administrator'),
    ('PRINCIPAL', 'School Principal'),
    ('DEPUTY_PRINCIPAL', 'Deputy Principal'),
    ('HOD', 'Head of Department'),
    ('ACCOUNTANT', 'Finance Manager'),
    ('BURSAR', 'School Bursar'),
    ('HR_OFFICER', 'HR Officer'),
    ('REGISTRAR', 'Registrar'),
    ('SECRETARY', 'School Secretary'),
    ('TEACHER', 'Teaching Staff'),
    ('LIBRARIAN', 'School Librarian'),
    ('NURSE', 'School Nurse'),
    ('SECURITY', 'Security Staff'),
    ('SECURITY_GUARD', 'Security Guard'),
    ('COOK', 'Kitchen / Cook'),
    ('STORE_CLERK', 'Store Clerk'),
    ('PARENT', 'Parent / Guardian'),
    ('STUDENT', 'Student'),
    ('ALUMNI', 'Alumni'),
]


def add_secretary_role(apps, schema_editor):
    Role = apps.get_model('school', 'Role')
    Role.objects.update_or_create(
        name='SECRETARY',
        defaults={'description': 'School Secretary'},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_financeauditlog_created_at_stable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=ROLE_NAME_CHOICES, max_length=50, unique=True),
        ),
        migrations.RunPython(add_secretary_role, migrations.RunPython.noop),
    ]
