# Generated by Django 4.2.30 on 2026-04-22 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0061_secretary_role_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorderitem',
            name='approved_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='quoted_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='approval_trail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='approved_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='document_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='office_owner',
            field=models.CharField(choices=[('FINANCE', 'Finance Office'), ('ADMIN', 'Administration')], default='FINANCE', max_length=10),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='procurement_type',
            field=models.CharField(choices=[('LPO', 'Local Purchase Order'), ('LSO', 'Local Supply Order')], default='LPO', max_length=3),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_store_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='received_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='receiving_state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Received')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='storeorderrequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_orders', to='school.storesupplier'),
        ),
    ]
