# Generated by Django 4.2.30 on 2026-04-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0062_procurement_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('doc', 'Document'), ('spreadsheet', 'Spreadsheet'), ('json', 'JSON'), ('xml', 'XML'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='module',
            field=models.CharField(choices=[('STUDENTS', 'Students'), ('ADMISSIONS', 'Admissions'), ('ACADEMICS', 'Academics'), ('STAFF', 'Staff'), ('HR', 'Human Resources'), ('FINANCE', 'Finance'), ('LIBRARY', 'Library'), ('TRANSPORT', 'Transport'), ('HOSTEL', 'Hostel'), ('ASSETS', 'Inventory & Assets'), ('CLOCKIN', 'Clock-In'), ('BRANDING', 'Branding'), ('COMMUNICATION', 'Communication'), ('REPORTING', 'Reporting'), ('SETTINGS', 'Settings'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
