# Generated by Codex on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0051_student_enforce_ulid_constraints"),
        ("hr", "0007_add_staff_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="school_department",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_department_profile",
                to="school.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="join_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
