# Generated by Codex on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_department_school_bridge_and_employee_field_relaxation"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="department_hr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_positions_stage",
                to="hr.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="department_hr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_employees_stage",
                to="hr.department",
            ),
        ),
        migrations.AddField(
            model_name="workschedule",
            name="department_hr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_schedules_stage",
                to="hr.department",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="department_hr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_job_postings_stage",
                to="hr.department",
            ),
        ),
    ]
