# Generated by Codex on 2026-03-30

from django.db import migrations


def _compat_department_code(school_department, HrDepartment):
    candidate = f"HRSD{school_department.id}"
    if not HrDepartment.objects.filter(code=candidate).exclude(school_department_id=school_department.id).exists():
        return candidate

    suffix = 1
    while True:
        next_candidate = f"HRSD{school_department.id}X{suffix}"
        if not HrDepartment.objects.filter(code=next_candidate).exists():
            return next_candidate
        suffix += 1


def _ensure_hr_department_for_school_department(school_department, HrDepartment, Employee):
    if school_department is None:
        return None

    existing = HrDepartment.objects.filter(school_department_id=school_department.id).first()
    if existing:
        return existing

    head_employee = None
    if school_department.head_id:
        head_employee = Employee.objects.filter(user_id=school_department.head_id).order_by("id").first()

    return HrDepartment.objects.create(
        name=school_department.name,
        code=_compat_department_code(school_department, HrDepartment),
        head_id=head_employee.id if head_employee else None,
        school_department_id=school_department.id,
        description=school_department.description or "",
        is_active=school_department.is_active,
    )


def backfill_hr_department_replacement_fields(apps, schema_editor):
    Position = apps.get_model("hr", "Position")
    Employee = apps.get_model("hr", "Employee")
    WorkSchedule = apps.get_model("hr", "WorkSchedule")
    JobPosting = apps.get_model("hr", "JobPosting")
    HrDepartment = apps.get_model("hr", "Department")

    def migrate_queryset(queryset):
        for row in queryset.select_related("department").order_by("id"):
            target = _ensure_hr_department_for_school_department(row.department, HrDepartment, Employee)
            if row.department_hr_id != (target.id if target else None):
                row.department_hr_id = target.id if target else None
                row.save(update_fields=["department_hr"])

    migrate_queryset(Position.objects.exclude(department_id__isnull=True))
    migrate_queryset(Employee.objects.exclude(department_id__isnull=True))
    migrate_queryset(WorkSchedule.objects.exclude(department_id__isnull=True))
    migrate_queryset(JobPosting.objects.exclude(department_id__isnull=True))


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_add_hr_department_replacement_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_hr_department_replacement_fields, migrations.RunPython.noop),
    ]
