# Generated by Codex on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_backfill_hr_department_replacement_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="department",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="department",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="department_hr",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="department_hr",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="workschedule",
            old_name="department_hr",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="jobposting",
            old_name="department_hr",
            new_name="department",
        ),
        migrations.AlterField(
            model_name="position",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_positions",
                to="hr.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_employees",
                to="hr.department",
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_schedules",
                to="hr.department",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_job_postings",
                to="hr.department",
            ),
        ),
    ]
