# Generated by Django 4.2.7 on 2026-04-02 11:05

from datetime import date

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


def _normalize_key(value):
    import re

    return re.sub(r"[^A-Z0-9]+", "", str(value or "").upper())


def _resolve_tenant_code(schema_editor):
    tenant = getattr(schema_editor.connection, "tenant", None)
    candidates = (
        getattr(tenant, "schema_name", None),
        getattr(schema_editor.connection, "schema_name", None),
    )
    for candidate in candidates:
        normalized = _normalize_key(candidate)
        if normalized and normalized != "PUBLIC":
            return normalized[:8]
    return "TENANT"


def backfill_staff_identity(apps, schema_editor):
    Employee = apps.get_model("hr", "Employee")
    tenant_code = _resolve_tenant_code(schema_editor)
    sequence_by_year = {}

    existing_ids = (
        Employee.objects.exclude(staff_id__isnull=True)
        .exclude(staff_id="")
        .values_list("staff_id", flat=True)
    )
    for staff_id in existing_ids:
        parts = str(staff_id).split("-")
        if len(parts) != 4 or parts[0] != "STF":
            continue
        year = parts[2]
        try:
            sequence = int(parts[3])
        except (TypeError, ValueError):
            continue
        sequence_by_year[year] = max(sequence_by_year.get(year, 0), sequence)

    queryset = Employee.objects.filter(Q(staff_id__isnull=True) | Q(staff_id="")).order_by("id")
    for employee in queryset.iterator():
        basis_date = employee.join_date or employee.created_at or date.today()
        year = str(getattr(basis_date, "year", date.today().year))
        sequence = sequence_by_year.get(year, 0) + 1
        candidate = f"STF-{tenant_code}-{year}-{sequence:05d}"
        while Employee.objects.filter(staff_id=candidate).exists():
            sequence += 1
            candidate = f"STF-{tenant_code}-{year}-{sequence:05d}"

        sequence_by_year[year] = sequence
        employee.staff_id = candidate
        update_fields = ["staff_id"]
        if not employee.onboarding_status:
            employee.onboarding_status = "PENDING"
            update_fields.append("onboarding_status")
        employee.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_finalize_hr_department_fk_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_role_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='onboarding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_PROVISIONING', 'Ready for Provisioning'), ('PROVISIONED', 'Provisioned')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_category',
            field=models.CharField(blank=True, choices=[('TEACHING', 'Teaching'), ('ADMIN', 'Admin'), ('SUPPORT', 'Support'), ('OPERATIONS', 'Operations'), ('HOSTEL', 'Hostel'), ('SECURITY', 'Security'), ('KITCHEN', 'Kitchen'), ('HEALTH', 'Health')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='blocks_account_provisioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='task_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('License', 'License'), ('Professional', 'Professional'), ('Registration', 'Registration'), ('Other', 'Other')], default='Certificate', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('institution', models.CharField(blank=True, max_length=180)),
                ('field_of_study', models.CharField(blank=True, max_length=180)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('year_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='hr/employees/qualifications/')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='hr.employee')),
            ],
            options={
                'ordering': ['-is_primary', '-year_obtained', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEmploymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kra_pin', models.CharField(blank=True, max_length=100)),
                ('nhif_number', models.CharField(blank=True, max_length=100)),
                ('nssf_number', models.CharField(blank=True, max_length=100)),
                ('tsc_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=180)),
                ('bank_branch', models.CharField(blank=True, max_length=180)),
                ('bank_account_name', models.CharField(blank=True, max_length=180)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('position_grade', models.CharField(blank=True, max_length=50)),
                ('salary_scale', models.CharField(blank=True, max_length=50)),
                ('probation_months', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmation_due_date', models.DateField(blank=True, null=True)),
                ('employment_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_profile', to='hr.employee')),
            ],
            options={
                'ordering': ['employee__employee_id'],
            },
        ),
        migrations.RunPython(backfill_staff_identity, migrations.RunPython.noop),
    ]
