# Generated by Django 4.2.7 on 2026-04-02 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0012_session6_staff_identity_backbone'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='alert_status',
            field=models.CharField(choices=[('NONE', 'None'), ('OPEN', 'Open'), ('AUTO_RESOLVED', 'Auto Resolved'), ('MANUALLY_RESOLVED', 'Manually Resolved')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('BIOMETRIC', 'Biometric'), ('BULK', 'Bulk'), ('RECONCILED', 'Reconciled')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='expected_check_in_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='payroll_feed_status',
            field=models.CharField(choices=[('READY', 'Ready'), ('BLOCKED_ALERT', 'Blocked - Alert'), ('BLOCKED_RECONCILIATION', 'Blocked - Reconciliation'), ('BLOCKED_LEAVE', 'Blocked - Leave')], default='READY', max_length=30),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='reconciliation_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scheduled_shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scheduled_shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='assignment_priority',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='staff_category_snapshot',
            field=models.CharField(blank=True, choices=[('TEACHING', 'Teaching'), ('ADMIN', 'Admin'), ('SUPPORT', 'Support'), ('OPERATIONS', 'Operations'), ('HOSTEL', 'Hostel'), ('SECURITY', 'Security'), ('KITCHEN', 'Kitchen'), ('HEALTH', 'Health')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_category', models.CharField(blank=True, choices=[('TEACHING', 'Teaching'), ('ADMIN', 'Admin'), ('SUPPORT', 'Support'), ('OPERATIONS', 'Operations'), ('HOSTEL', 'Hostel'), ('SECURITY', 'Security'), ('KITCHEN', 'Kitchen'), ('HEALTH', 'Health')], default='', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('working_days', models.JSONField(default=list)),
                ('break_duration_minutes', models.PositiveIntegerField(default=60)),
                ('grace_minutes', models.PositiveIntegerField(default=15)),
                ('requires_biometric_clock', models.BooleanField(default=False)),
                ('overtime_eligible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_templates', to='hr.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_templates', to='hr.position')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField()),
                ('expected_shift_start', models.TimeField(blank=True, null=True)),
                ('grace_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('AUTO_RESOLVED', 'Auto Resolved'), ('ESCALATED', 'Escalated'), ('MANUALLY_RESOLVED', 'Manually Resolved')], default='OPEN', max_length=20)),
                ('hr_copied', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_alerts', to='hr.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_alerts', to='hr.employee')),
                ('notified_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_absence_alerts', to='hr.employee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_absence_alerts', to=settings.AUTH_USER_MODEL)),
                ('shift_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_alerts', to='hr.shifttemplate')),
            ],
            options={
                'ordering': ['-alert_date', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='shift_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr.shifttemplate'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='shift_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_assignments', to='hr.shifttemplate'),
        ),
        migrations.AddConstraint(
            model_name='absencealert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'attendance_record'), name='uniq_active_absence_alert_per_attendance'),
        ),
    ]
