# Generated by Django 4.2.7 on 2026-04-02 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0013_attendancerecord_alert_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approval_stage',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager'), ('PENDING_HR', 'Pending HR'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_HR', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_hr_approved_requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='long_leave_threshold_days_snapshot',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_manager_approved_requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='requires_dual_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='return_reconciliation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TeachingSubstituteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('class_context', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absent_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_substitute_absences', to='hr.employee')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_substitute_assignments', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_substitute_assignments', to='hr.attendancerecord')),
                ('substitute_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_substitute_coverages', to='hr.employee')),
            ],
            options={
                'ordering': ['-assignment_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnToWorkReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REOPENED', 'Reopened')], default='PENDING', max_length=20)),
                ('extension_required', models.BooleanField(default=False)),
                ('attendance_correction_required', models.BooleanField(default=False)),
                ('payroll_hold_required', models.BooleanField(default=False)),
                ('substitute_closed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_to_work_reconciliations', to='hr.attendancerecord')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_return_to_work_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_to_work_reconciliations', to='hr.employee')),
                ('leave_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_reconciliation', to='hr.leaverequest')),
            ],
            options={
                'ordering': ['-expected_return_date', '-updated_at', '-id'],
            },
        ),
    ]
