# Generated by Django 4.2.7 on 2026-04-02 17:14

from datetime import date
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


KENYA_DEFAULT_RULES = [
    {
        'code': 'PAYE',
        'name': 'Pay As You Earn',
        'calculation_method': 'BAND',
        'base_name': 'TAXABLE_PAY',
        'employee_rate': Decimal('0.00'),
        'employer_rate': Decimal('0.00'),
        'fixed_amount': Decimal('0.00'),
        'minimum_amount': Decimal('0.00'),
        'maximum_amount': None,
        'relief_amount': Decimal('2400.00'),
        'is_kenya_default': True,
        'is_mandatory': True,
        'effective_from': date(2023, 7, 1),
        'priority': 100,
        'configuration_notes': (
            'Kenya PAYE monthly bands as published by KRA under the Finance Act 2023, '
            'effective July 1, 2023.'
        ),
        'bands': [
            {'lower_bound': Decimal('0.00'), 'upper_bound': Decimal('24000.00'), 'employee_rate': Decimal('10.00')},
            {'lower_bound': Decimal('24000.00'), 'upper_bound': Decimal('32333.00'), 'employee_rate': Decimal('25.00')},
            {'lower_bound': Decimal('32333.00'), 'upper_bound': Decimal('500000.00'), 'employee_rate': Decimal('30.00')},
            {'lower_bound': Decimal('500000.00'), 'upper_bound': Decimal('800000.00'), 'employee_rate': Decimal('32.50')},
            {'lower_bound': Decimal('800000.00'), 'upper_bound': None, 'employee_rate': Decimal('35.00')},
        ],
    },
    {
        'code': 'NSSF',
        'name': 'National Social Security Fund',
        'calculation_method': 'BAND',
        'base_name': 'PENSIONABLE_PAY',
        'employee_rate': Decimal('0.00'),
        'employer_rate': Decimal('0.00'),
        'fixed_amount': Decimal('0.00'),
        'minimum_amount': Decimal('0.00'),
        'maximum_amount': None,
        'relief_amount': Decimal('0.00'),
        'is_kenya_default': True,
        'is_mandatory': True,
        'effective_from': date(2026, 2, 1),
        'priority': 200,
        'configuration_notes': (
            'Kenya NSSF year 4 contribution rates from February 2026: tier I lower limit '
            'Ksh 9,000 and upper limit Ksh 108,000 at 6% employee and 6% employer.'
        ),
        'bands': [
            {
                'lower_bound': Decimal('0.00'),
                'upper_bound': Decimal('9000.00'),
                'employee_rate': Decimal('6.00'),
                'employer_rate': Decimal('6.00'),
            },
            {
                'lower_bound': Decimal('9000.00'),
                'upper_bound': Decimal('108000.00'),
                'employee_rate': Decimal('6.00'),
                'employer_rate': Decimal('6.00'),
            },
        ],
    },
    {
        'code': 'SHIF',
        'name': 'Social Health Insurance Fund',
        'calculation_method': 'PERCENT',
        'base_name': 'GROSS_PAY',
        'employee_rate': Decimal('2.75'),
        'employer_rate': Decimal('0.00'),
        'fixed_amount': Decimal('0.00'),
        'minimum_amount': Decimal('300.00'),
        'maximum_amount': None,
        'relief_amount': Decimal('0.00'),
        'is_kenya_default': True,
        'is_mandatory': True,
        'effective_from': date(2024, 10, 1),
        'priority': 300,
        'configuration_notes': (
            'SHA guidance states SHIF contribution is 2.75% of household income with a '
            'minimum monthly premium of Ksh 300.'
        ),
        'bands': [],
    },
    {
        'code': 'HOUSING_LEVY',
        'name': 'Affordable Housing Levy',
        'calculation_method': 'PERCENT',
        'base_name': 'GROSS_PAY',
        'employee_rate': Decimal('1.50'),
        'employer_rate': Decimal('1.50'),
        'fixed_amount': Decimal('0.00'),
        'minimum_amount': Decimal('0.00'),
        'maximum_amount': None,
        'relief_amount': Decimal('0.00'),
        'is_kenya_default': True,
        'is_mandatory': True,
        'effective_from': date(2024, 3, 19),
        'priority': 400,
        'configuration_notes': (
            'KRA Affordable Housing Levy collection notice: employee 1.5% of gross salary '
            'and employer 1.5% of gross salary from March 19, 2024.'
        ),
        'bands': [],
    },
]


def seed_kenya_first_statutory_defaults(apps, schema_editor):
    rule_model = apps.get_model('hr', 'StatutoryDeductionRule')
    band_model = apps.get_model('hr', 'StatutoryDeductionBand')
    for definition in KENYA_DEFAULT_RULES:
        bands = definition['bands']
        defaults = {key: value for key, value in definition.items() if key != 'bands'}
        rule, _ = rule_model.objects.get_or_create(
            code=definition['code'],
            effective_from=definition['effective_from'],
            defaults=defaults,
        )
        for index, band in enumerate(bands, start=1):
            band_model.objects.get_or_create(
                rule=rule,
                display_order=band.get('display_order', index),
                defaults={
                    'lower_bound': band['lower_bound'],
                    'upper_bound': band['upper_bound'],
                    'employee_rate': band.get('employee_rate', Decimal('0.00')),
                    'employer_rate': band.get('employer_rate', Decimal('0.00')),
                    'fixed_amount': band.get('fixed_amount', Decimal('0.00')),
                    'additional_amount': band.get('additional_amount', Decimal('0.00')),
                    'is_active': True,
                },
            )


def reverse_kenya_first_statutory_defaults(apps, schema_editor):
    rule_model = apps.get_model('hr', 'StatutoryDeductionRule')
    for definition in KENYA_DEFAULT_RULES:
        rule_model.objects.filter(
            code=definition['code'],
            effective_from=definition['effective_from'],
            is_kenya_default=True,
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0055_journalline_vote_head'),
        ('hr', '0014_leaverequest_approval_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryDeductionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PAYE', 'PAYE'), ('NSSF', 'NSSF'), ('SHIF', 'SHIF'), ('HOUSING_LEVY', 'Housing Levy'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('calculation_method', models.CharField(choices=[('BAND', 'Band'), ('PERCENT', 'Percent'), ('FIXED', 'Fixed')], default='PERCENT', max_length=20)),
                ('base_name', models.CharField(default='GROSS_PAY', max_length=50)),
                ('employee_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('employer_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('relief_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('is_kenya_default', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('configuration_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'code', '-effective_from', 'id'],
            },
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='blocked_item_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_disbursed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='exception_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='finance_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='finance_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_finance_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='statutory_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='workforce_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='attendance_deduction_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='block_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='calculation_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='employer_statutory_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='other_deduction_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='posting_bucket',
            field=models.CharField(blank=True, choices=[('TEACHING_SALARIES', 'Teaching Salaries'), ('OPERATIONS_SALARIES', 'Operations Salaries'), ('SUPPORT_SALARIES', 'Support Salaries')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='statutory_deduction_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payrollbatch',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Ready for Finance Approval', 'Ready for Finance Approval'), ('Finance Approved', 'Finance Approved'), ('Disbursement In Progress', 'Disbursement In Progress'), ('Paid', 'Paid'), ('Disbursed', 'Disbursed'), ('Finance Posted', 'Finance Posted'), ('Closed', 'Closed')], default='Draft', max_length=40),
        ),
        migrations.CreateModel(
            name='StatutoryDeductionBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('employee_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('employer_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='hr.statutorydeductionrule')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItemBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('ATTENDANCE_DEDUCTION', 'Attendance Deduction'), ('STATUTORY_EMPLOYEE', 'Statutory Employee'), ('STATUTORY_EMPLOYER', 'Statutory Employer'), ('OTHER_DEDUCTION', 'Other Deduction')], max_length=30)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_rows', to='hr.payrollitem')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash'), ('MOBILE', 'Mobile'), ('MIXED', 'Mixed')], default='BANK', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_disbursements', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='hr.payrollbatch')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollFinancePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_stage', models.CharField(choices=[('ACCRUAL', 'Accrual'), ('DISBURSEMENT', 'Disbursement')], max_length=20)),
                ('entry_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('vote_head_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashbook_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_postings', to='school.cashbookentry')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_postings', to='school.journalentry')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_postings', to='hr.payrollbatch')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_finance_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('payroll', 'posting_stage')},
            },
        ),
        migrations.RunPython(seed_kenya_first_statutory_defaults, reverse_kenya_first_statutory_defaults),
    ]
