# Generated by Django 4.2.7 on 2026-04-02 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0015_statutorydeductionrule_payrollbatch_approval_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="archive_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_hr_employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Acting", "Acting"),
                    ("On Leave", "On Leave"),
                    ("Suspended", "Suspended"),
                    ("Terminated", "Terminated"),
                    ("Retired", "Retired"),
                    ("Archived", "Archived"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StaffLifecycleEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_group",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Transfer"),
                            ("CAREER", "Career"),
                            ("DISCIPLINE", "Discipline"),
                            ("EXIT", "Exit"),
                            ("CLEARANCE", "Clearance"),
                            ("ARCHIVE", "Archive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=160)),
                ("summary", models.TextField(blank=True)),
                ("status_snapshot", models.CharField(blank=True, max_length=40)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source_model", models.CharField(blank=True, max_length=120)),
                ("source_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_events",
                        to="hr.employee",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_staff_lifecycle_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-occurred_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="stafftransfer",
            name="to_position_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_transfer_targets",
                to="hr.position",
            ),
        ),
    ]
