# Generated by Django 4.2.7 on 2026-04-02 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0016_session9_staff_lifecycle_controls"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffCareerAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("PROMOTION", "Promotion"),
                            ("DEMOTION", "Demotion"),
                            ("ACTING_APPOINTMENT", "Acting Appointment"),
                            ("ACTING_APPOINTMENT_END", "Acting Appointment End"),
                        ],
                        max_length=30,
                    ),
                ),
                ("from_position_title", models.CharField(blank=True, max_length=150)),
                ("to_position_title", models.CharField(blank=True, max_length=150)),
                ("target_position_grade", models.CharField(blank=True, max_length=50)),
                ("target_salary_scale", models.CharField(blank=True, max_length=50)),
                ("reason", models.TextField(blank=True)),
                ("effective_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("EFFECTIVE", "Effective"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("previous_assignment_snapshot", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_staff_career_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_actions",
                        to="hr.employee",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_actions_from",
                        to="hr.department",
                    ),
                ),
                (
                    "from_position_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_actions_from",
                        to="hr.position",
                    ),
                ),
                (
                    "parent_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_up_actions",
                        to="hr.staffcareeraction",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_staff_career_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_actions_to",
                        to="hr.department",
                    ),
                ),
                (
                    "to_position_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_actions_to",
                        to="hr.position",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-created_at", "-id"],
            },
        ),
    ]
