# Generated by Django 4.2.7 on 2026-04-02 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0017_session9_staff_career_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplinaryCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_number", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(max_length=80)),
                ("opened_on", models.DateField(default=django.utils.timezone.localdate)),
                ("incident_date", models.DateField(blank=True, null=True)),
                ("summary", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed"), ("CANCELLED", "Cancelled")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADVISORY", "Advisory"),
                            ("WARNING", "Warning"),
                            ("SUSPENSION", "Suspension"),
                            ("DISMISSAL", "Dismissal"),
                            ("EXONERATED", "Exonerated"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_hr_disciplinary_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_cases",
                        to="hr.employee",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_hr_disciplinary_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_on", "-created_at", "-id"],
            },
        ),
    ]
