# Generated by Django 4.2.7 on 2026-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0007_rename_clockin_cap_ts_idx_clockin_att_timesta_7b8e76_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdevice',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Device login password. Required for sync/export. Dahua factory default is "admin123" — change it on the device and enter the new password here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='smartpsssource',
            name='password',
            field=models.CharField(blank=True, default='', help_text='SmartPSS Lite login password. Required for sync. Enter the password configured in SmartPSS Lite.', max_length=200),
        ),
    ]
