# Generated by Django 4.2.7 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0008_remove_hardcoded_device_password_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='ip_version',
            field=models.CharField(
                choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')],
                default='ipv4',
                help_text='Select IPv4 or IPv6 for the device network address.',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='smartpsssource',
            name='ip_version',
            field=models.CharField(
                choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')],
                default='ipv4',
                help_text='Select IPv4 or IPv6 when the SmartPSS host is an IP literal.',
                max_length=10,
            ),
        ),
    ]
